#!/bin/sh
 
ssh app@dockerr.eastus2.cloudapp.azure.com <<EOF
  cd ~/hello-jenkins
  git pull
  npm install --production
  forever stopall
  forever start app.js
  docker run -it munisanath/rediscache /bin/bash/
  mkdir muni
  exit
EOF
